### PR TITLE
Update bootstrap to 3.2.0

### PR DESCRIPTION
**Pull request by jaimerson**
Still a work in progress. I'm not sure if there are any "hidden" views aside from the ones accessible through the navbar.
TODO:
Align some things;
Verify which ones were already misaligned before upgrading and try to align those as well;
Hunt any weird bugs caused by the upgrade;
Here is a sample `invoices/show`:
image

### CODE REVIEW

**Comment by jaimerson** [comment]
Also, is there any special reason why there's a vendored bootstrap 2.1 along with the gem one?

**Comment by sbrossie** [comment]
There are a few views that are not visible from the nav bar:
* /admin_tenants
* /admin_allowed_users
* /tenants

Regarding the additional version of bootstrap 2.1  (vendor package), i don't any reasons; probably a mistake. Feel free to remove.

**Comment by jaimerson** [comment]
Alright, thanks

**Comment by jaimerson** [comment]
Update: image

**Pull request closed without merging**
