### PR TITLE
[WIP] Responsive improvements

### PR DESCRIPTION
**Pull request by jaimerson**

### CODE REVIEW

**Comment by sbrossie** [comment]
@jaimerson I am bit unclear what is the status? Should we expect more commits? Should we start reviewing/merging this one and if so, what exactly did that fix?

**Comment by sbrossie** [comment]
@jaimerson Did we lose you?

**Comment by jaimerson** [comment]
Hello!
Here's the current look and feel with the responsive fixes. Let me know what you think.

image
image
image
image
image
image

**Comment by sbrossie** [comment]
@jaimerson Thanks for the PR. We will take a look in the next few days and get back to you with comments.

**Comment by jaimerson** [comment]
Build is failing with ruby < 2.0 because of this dependency:
image
Maybe the rails version should be more restrictive? Or should we open an issue on [rails/rails]9github.com/rails/rails), as a minor version should not break this kind of compatibility?

**Comment by pierre** [comment]
> Maybe the rails version should be more restrictive?

Are you sure it's a direct dependency of Rails? Could it be from [mail](https://github.com/mikel/mail/commit/d4ffe72b0b2b0c6c8a49130bfe8e792d0542ac0e#diff-14e7b9ff4be93907e44a6fb43e2d3e0d) instead?

Maybe we could enforce the version of `mime-types-data` to be `< 3`?

**Comment by pierre** [comment]
@jaimerson I'm seeing a weird behavior on desktop with the top menu. Do you have the same issue?

image

Also, did you have a chance to look at the build?

**Comment by jaimerson** [comment]
@pierre by weird behavior you mean the `user` menu on the right? I thought that was the expected behavior.
I still haven't had the time to fix the tests. Is there anything else you noticed?

**Comment by pierre** [comment]
Not just the `user` menu on the right: all of it (I also see a blank square on the far left). You can see how it should look like on http://demo.killbill.io/ (username `demo_ro`, password `demo_ro`).

I see other regressions on Desktop, for example the account submenu:


image

**Comment by jaimerson** [comment]
There you go, pinned mime-types to `< 3`

**Comment by pierre** [comment]
Cool. Were you also able to reproduce the regressions on Desktop?

**Comment by jaimerson** [comment]
Yes, I'm working on it.

**Comment by jaimerson** [comment]
image

**Comment by jaimerson** [comment]
image

**Comment by jaimerson** [comment]
I guess this fixes all the regressions (unless you prefer the `username/sign out`, in which case I'll remove the dropdown). Let me know what you think.

**Comment by jaimerson** [comment]
Ipad size
image

**Comment by sbrossie** [comment]
@jaimerson Pierre and I went through a detailed review for both browser (regression), iPad landscape and iPad portrait. At the very minimum we need to make sure current browser look & feel is unchanged (or minimal acceptable changes) and iPad landscape issues we originally reported get fixed. I suggest to drop iPad portrait for now (there is one main issue to fix, we can come back to it later).

Note that both code are up and in the cloud, current version is [here](http://demo.killbill.io/) and the one with your PR is [here](http://ec2-52-34-80-100.us-west-2.compute.amazonaws.com:3100/) so you can compare the two easily.

**Browser regression**
* Top menu is broken (we miss the plug icon to access plugins)
* Login/tenant info got capitalize
* Everything is wider (becomes obvious if you open both tab side by side and switch from one to the next quickly)

**iPad landscape**
Those were the original items i had listed in my email to you:

1. on iPad (landscape), the 'plugin' and 'setting' icon are on top of each other: 
2. The search bottom is a bit broken (message 'showing X results' overlaps with tabs 'First)
still broken. 
3. Analytics : in landscape, the box for the date is too small


**Resolution for item 1**: You introduced a new `Hamburger` menu. **Ideally we would like to keep the icons as they were and simply fix the alignment for the iPad**. So, let's try to explore that path first and if this gets too difficult, we are also open to introduce the hamburger menu (but not ideal because we now end up sub-menus and so this is more clicks and complication than needed). The hamburger menu also has quite a few issues:

* contains menu of menu and then we miss the plugin sub-menu 
* shows up as blue
* too large
* center aligned
* lays on top of search bar
* title for the icons inside (sub-menu) are incorrect. Those don't exist today because we simply list the icons with no text so if we need to add text, we 'll have to think define it.

**Resolution for item 2**: Not fixed

**Resolution for item 3**: Not fixed

**Comment by jaimerson** [comment]
About the plugins: I could not find any mention to those links on this codebase (for example, search for `fa-plug` in this repository, no results). Maybe there are commits in the demo that are not here yet. Anyway, I'll just add it to finish the fixes in the ui.

**Comment by jaimerson** [comment]
See #63

**Pull request closed without merging**
