### PR TITLE
Format date to - The ISO 8601 date format (%Y-%m-%d)

### PR DESCRIPTION
**Pull request by kpbacode**
This PR address fallowing issue:  https://github.com/killbill/killbill-admin-ui/issues/272
The ISO 8601 date format (%Y-%m-%d)

To do tests.

### CODE REVIEW

**Comment by kpbacode** [comment]
Screenshot 2022-10-17 at 10 55 36

Changed Gemfile from http to https

**Comment by kpbacode** [comment]
There is definition of date_only already 👍 will update this code for this variable.
Date::DATE_FORMATS[:date_only] = "%Y-%m-%d"

**Comment by pierre** [comment]
Why this change?

The backend should support fully qualified datetimes: https://github.com/killbill/killbill/blob/4da84cfb3722575d7c232fbae1d4e01d0dbfbef4/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/AdminResource.java#L175-L176

**Comment by kpbacode** [comment]
Screenshot 2022-10-17 at 20 04 55

Will check tomorrow morning. I was getting similar errors, malformed HHMMSS.

**Comment by kpbacode** [comment]
Screenshot 2022-10-18 at 05 42 04

`http://localhost:3000/queues?account_id=6d37b370-3358-4dee-a3f3-b1620f887e87&with_history=true&min_date=1970-01-01`

Screenshot 2022-10-18 at 05 37 43

**Comment by kpbacode** [comment]
With  `ISO-8601 | 2022-10-18T03:57:32+0000` works fine.

**Comment by pierre** [comment]
👍 Do we still need that PR then? The code is identical (just reformatted)?

**Comment by kpbacode** [comment]
yes it fixing my bug from first commit, forgot to add `( )`
Screenshot 2022-10-19 at 06 23 08

**Comment by pierre** [comment]
Ohhhh, good catch! Very subtle...

**Pull request merged**
